### ISSUE TITLE
Properly show/set up the shopping cart and get it to populate the right way

### ISSUE THREAD

**Issue by gadtfly** [jaiwil1221/gemma#2]

**Comment by gadtfly** [comment]
What exactly is not working here?  I seem to be able to add items to the shopping cart successfully, and see it both in the navbar dropdown and on the `/cart` view.

**Comment by jaiwil1221** [comment]
I can't remove any products - I need to figure that part out. I'm going to try to have this done before our call.

**Comment by gadtfly** [comment]
According to the [`acts_as_shopping_cart` docs](https://github.com/crowdint/acts_as_shopping_cart#remove-items), to remove a `Listing` from a cart, we need the `ShoppingCart` instance we're working on, and we need the `Listing` instance that we want to remove from it.  Once we have those 2 things, we can call:

```ruby
@shopping_cart.remove(@listing, 1)
```

So, we need to write a controller action that gets those instances, then calls that method.  Let's call it `ShoppingCartsController#destroy`
> Though it would be more correct to set it up as `ShoppingCartItemsController#destroy`.  `ShoppingCartController#destroy` [suggests it should destroy the whole shopping cart](https://blog.apigee.com/detail/does_your_api_need_to_be_truly_restful).  Feel free to make this correction, but to be consistent you would need to refactor the route and controller for adding to the cart as well.

`@shopping_cart` is currently implicitly available in all controller actions due to the [callback in the `ApplicationController` which sets it](https://github.com/jaiwil1221/gemma/blob/master/app/controllers/application_controller.rb#L21).

We can get the `Listing` if we have its `listing_id`.  So we'll need a `listing_id` to come through in params.  There are [several ways](http://guides.rubyonrails.org/routing) to set this up, but in this case might as well use the same approach [we're already using to send a `listing_id` to `ShopingCartController#create`](https://github.com/jaiwil1221/gemma/blob/master/app/views/listings/show.html.erb#L18):

Set up a route to dispatch `DELETE /shopping_carts` to `ShoppingCartControllers#destroy` (which you may already have -- check your `routes.rb` and `rake routes`).  Then craft a link to send `DELETE /shopping_carts?listing_id=actual-listing-id`.

That should be it.

**Comment by jaiwil1221** [comment]
Added this to cart form: 
<%= link_to '', delete_path(:listing_id => @listing), method: :delete, class: "fa fa-minus-square" %></td>

Added this to ShoppingCartsController:

def destroy
    @listing = Listing.find_by(params[:listing]).id
    @shopping_cart.remove(@listing, 1)
    redirect_to cart_path
  end

No error, but no change either. The item stays in the cart.

Server says:
Started DELETE "/cart" for ::1 at 2015-03-04 04:00:44 -0600
Processing by ShoppingCartsController#cart as HTML
  Parameters: {"authenticity_token"=>"0CsVJDiDUgYensX9fHvJrU92/TpyPXsaZIADLyfjnmeTQ/vZA/g3e5mfOjj5ilkHuvHY4D8KA+jpPoBKq0Vtpg=="}
  ShoppingCart Load (0.3ms)  SELECT  "shopping_carts".* FROM "shopping_carts" WHERE "shopping_carts"."id" = ? LIMIT 1  [["id", 4]]
  ShoppingCartItem Load (0.1ms)  SELECT "shopping_cart_items".* FROM "shopping_cart_items" WHERE "shopping_cart_items"."owner_id" = ? AND "shopping_cart_items"."owner_type" = ?  [["owner_id", 4], ["owner_type", "ShoppingCart"]]
  Listing Load (0.1ms)  SELECT  "listings".* FROM "listings" WHERE "listings"."id" = ? LIMIT 1  [["id", 19]]
  ShoppingCartItem Load (0.1ms)  SELECT  "shopping_cart_items".* FROM "shopping_cart_items" WHERE "shopping_cart_items"."owner_id" = ? AND "shopping_cart_items"."owner_type" = ? AND "shopping_cart_items"."item_id" IS NULL  ORDER BY "shopping_cart_items"."id" ASC LIMIT 1  [["owner_id", 4], ["owner_type", "ShoppingCart"]]
  Rendered shopping_carts/cart.html.erb within layouts/application (7.3ms)
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 12]]
  Category Load (0.1ms)  SELECT "categories".* FROM "categories"
  Rendered shopping_carts/_shopping_cart.html.erb (1.9ms)
  Rendered layouts/_nav.html.erb (5.0ms)
  Rendered layouts/_footer.html.erb (0.1ms)
Completed 200 OK in 303ms (Views: 300.7ms | ActiveRecord: 0.9ms)

**Comment by gadtfly** [comment]
Just looking at the log alone:

```
Started DELETE "/cart" for ::1 at 2015-03-04 04:00:44 -0600
Processing by ShoppingCartsController#cart as HTML
Parameters: {"authenticity_token"=>"0CsVJDiDUgYensX9fHvJrU92/TpyPXsaZIADLyfjnmeTQ/vZA/g3e5mfOjj5ilkHuvHY4D8KA+jpPoBKq0Vtpg=="}
```

ie: "The link sent `DELETE /cart`, which was routed to `ShoppingCartsController#cart`, and did not result in there being any `listing_id` in `params`."

----

----

```ruby
<%= link_to '', delete_path(:listing_id => @listing), method: :delete, class: "fa fa-minus-square" %>
```

`delete_path(:listing_id => @listing)` certainly looks like it should result in there being a `params[:listing_id]`.  But not if `@listing` is `nil`.  Which listing is this link supposed to remove?

----

The route you're hitting here is [defined in `routes.rb`](https://github.com/jaiwil1221/gemma/blob/master/config/routes.rb#L28) as:

```ruby
delete 'cart' => 'shopping_carts#cart', as: 'delete' 
```

Which is why it's going to `ShoppingCartsController#cart` (which doesn't actually exist -- Rails is being generous and just bypassing the controller and rendering the view `views/shoppings_carts/cart.html.erb`), and not `ShoppingCartsController#destroy` (which is where you put your logic).

The `as:` option just determines what the `_path` helper will be called, in this case generating `delete_path`

So you should either change this route to target the intended controller action (`shopping_carts#destroy`), or have your link hit a different route that's already set up to target the action ([hint](https://github.com/jaiwil1221/gemma/blob/master/config/routes.rb#L10))

----

Fix these 2 things, and when you click one of those links, your logs should be telling you:

"The link sent `DELETE /shopping_cart`, which was routed to `ShoppingCartsController#destroy`, with `params={listing_id: <some number>}`."

**Comment by gadtfly** [comment]
Also, in the controller method:

```ruby
@listing = Listing.find_by(params[:listing]).id
```

is going to give you a `NoMethodError 'id' for nil:NilClass`:

`Listing.find_by(params[:listing])` is going to return `nil`.  Then you're calling `nil.id`, hence the error.  What you are looking for is either `Listing.find_by(id: params[:listing_id])` or `Listing.find(params[:listing_id])` for short
